# Generated by Django 4.2.1 on 2023-05-30 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('legs', (('ht', 'hip thrust'), ('kas', 'kas glute bridge'), ('sht', 'single-leg hip thrust'), ('be', 'back extension'), ('s', 'squat'), ('bss', 'BSS'), ('rdl', 'RDL'), ('dl', 'deadlift'), ('su', 'step-ups'))), ('upper-body', (('bc', 'bicep curls'), ('hc', 'hammer curls'), ('pu', 'pull-ups'))), ('abs', (('io', 'in-n-outs'), ('pl', 'plank'), ('spl', 'side plank'), ('hd', 'hip dips'), ('vs', 'v-sit'))), ('cardio', (('jo', 'jo'), ('bi', 'bike'), ('st', 'stair master')))], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('type', models.CharField(choices=[('wa', 'warmup'), ('wo', 'working')], max_length=300)),
                ('reps', models.IntegerField()),
                ('specs', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('s', 'seconds'), ('min', 'minutes')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.CharField(default='17:32:14', max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2023, 5, 30))),
                ('time_start', models.DateTimeField(default=datetime.datetime(2023, 5, 30, 17, 32, 14, 306095))),
                ('time_end', models.DateTimeField(default=datetime.datetime(2023, 5, 30, 17, 32, 14, 306095))),
                ('length', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
