# Generated by Django 4.2.1 on 2023-05-30 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_workout_id_alter_workout_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='details',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default='10'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='specs',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('s', 'seconds'), ('min', 'minutes')], default=('kg', 'kg'), max_length=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='val',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(default='21:46:03', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='21:46:03', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 21, 46, 3, 195407)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 21, 46, 3, 195407)),
        ),
    ]
