# Generated by Django 4.2.1 on 2023-05-30 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_exercise_id_alter_workout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(default='05/31/2023, 11:39:28', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='05/31/2023, 11:39:28', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 11, 39, 28, 208320)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 11, 39, 28, 208320)),
        ),
    ]
