# Generated by Django 4.2.1 on 2023-05-31 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_exercise_id_alter_workout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout_id',
            field=models.CharField(default='05/31/2023, 13:04:14', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='05/31/2023, 13:04:14', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 4, 14, 144152)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 4, 14, 144152)),
        ),
    ]
