# Generated by Django 4.2.1 on 2023-05-31 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_exercise_workout_id_alter_exercise_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.CharField(default='05/31/2023, 17:10:24', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='05/31/2023, 17:10:24', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 17, 10, 24, 961489)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 17, 10, 24, 961489)),
        ),
    ]
