# Generated by Django 4.2.1 on 2023-05-31 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_workout_status_alter_exercise_workout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.CharField(default='05/31/2023, 22:46:04', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='05/31/2023, 22:46:04', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 22, 46, 4, 277807)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 22, 46, 4, 277807)),
        ),
    ]
