# Generated by Django 4.2.1 on 2023-05-31 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_exercise_exercise_alter_exercise_workout_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.CharField(default='06/01/2023, 01:52:45', max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='exercise',
            field=models.CharField(choices=[('legs', (('ht', 'hip thrust'), ('kas', 'kas glute bridge'), ('sht', 'single-leg hip thrust'), ('be', 'back extension'), ('s', 'squat'), ('bss', 'BSS'), ('rdl', 'RDL'), ('dl', 'deadlift'), ('su', 'step-ups'))), ('upper-body', (('bc', 'bicep curls'), ('hc', 'hammer curls'), ('pu', 'pull-ups'))), ('abs', (('io', 'in-n-outs'), ('pl', 'plank'), ('spl', 'side plank'), ('hd', 'hip dips'), ('vs', 'v-sit'))), ('cardio', (('jo', 'jo'), ('bi', 'bike'), ('st', 'stair master')))], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='01062023_01:52:45', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 1, 52, 45, 747340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 1, 52, 45, 741394, tzinfo=datetime.timezone.utc)),
        ),
    ]
