# Generated by Django 4.2.1 on 2023-05-31 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_delete_set_note_note_alter_exercise_workout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.CharField(default='06/01/2023, 04:08:03', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='01062023_04:08:03', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 4, 8, 3, 524009, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 4, 8, 3, 520999, tzinfo=datetime.timezone.utc)),
        ),
    ]
