# Generated by Django 4.2.1 on 2023-05-31 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_exercise_sets_alter_exercise_workout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.CharField(default='06/01/2023, 04:19:08', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(default='01062023_04:19:08', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 4, 19, 8, 787887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 4, 19, 8, 783556, tzinfo=datetime.timezone.utc)),
        ),
    ]
